### ISSUE TITLE
tracking issue for Dart 2 work

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#337]
- [ ] ignore the strongMode flag, and run all analysis in strong mode
  - [ ] remove the strongMode param from the restful API
- [x] upgrade the sdk used for the dartpad backend to a 2.0.0-dev version
- [ ] add a `dart2` param to the restful API
- [ ] use `dart2` to indicate --preview-dart-2 analysis and --preview-dart-2 compiles #334

@jakobr-google, I jotted down some todos for incremental migration to --preview-dart-2; feel free to re-do this or track elsewhere as you see fit :)

**Comment by devoncarew** [comment]
Progress on the front-end here: https://github.com/dart-lang/dart-pad/pull/801

**Comment by mit-mit** [comment]
@devoncarew do we have a dart2js that supports dart2 yet?

**Comment by devoncarew** [comment]
@sigmundch; not to my knowledge, but that's not necessary to start on this. Changing to the very latest version of dart2js (w/ full 2.0 support) could be the last 5%.

**Comment by sigmundch** [comment]
We are getting close on the dart2js side. To enable it: pass `--preview-dart-2` to dart2js.

Note: code will be larger and possibly slower given all the additional tracking of type variabels and runtime checks. You can regain some of that regression by turning off implicit runtime checks from strong mode (flag `--omit-implicit-checks`).

**Comment by mit-mit** [comment]
We got some other urgent work, so we were hoping to wait until this is actually supported. Let's shoot for beta 4.

**Comment by sigmundch** [comment]
I mentioned this elsewhere, but just to update here: dart2js support for `--preview-dart-2` is now ready.

**Comment by sigmundch** [comment]
I mentioned this elsewhere, but just to update here: dart2js support for `--preview-dart-2` is ready.

**Comment by jcollins-g** [comment]
Dart 2 support is deployed.  There are still some cleanup tasks to do to remove the old support, but closing the main issue as we've reached the milestone of Dart 2 by default.
